baseURL = "https://beta.ignite.no"
DefaultContentLanguage = "no"
languageName = "Norwegian"
languageCode = "no"
title = "Ignite Procurement"
publishDir = "docs"
weight = 1

[params]
logo = "/images/logo.svg"

# Header
header = "Reduser dine innkjøpskostnader"
description = "Vi hjelper deg med å optimaliser dine innkjøp ved hjelp av vårt verktøy Ignite Analytics og våre konsulenter som er eksperter på strategiske innkjøp."
image = "/images/infographics/dashboard2.svg"


[languages]
  [languages.no]
    languageName = "Norwegian"
    languageCode = "no"
    weight = "1"

  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = "2"

[[languages.no.menu.main]]
url    = "/"
name   = "Hjem"
weight = "0"

 
[[languages.no.menu.main]]
    name = "Ignite Analytics"
     identifier = "ignite-analytics"
     title = "Ignite Analytics"
     url = "/ignite-analytics/"
     weight = "1"

[[languages.no.menu.main]]
    name = "Ignite Academy"
     identifier = "ignite-academy"
     title = "Ignite Academy"
     url = "/ignite-academy/"
     weight = "2"

[[languages.no.menu.main]]
     name = "Ignite Services"
     identifier = "ignite-services"
     title = "Ignite Services"
     url = "/ignite-services/"
     id = "ignite-services"
     weight = "3"

[[languages.no.menu.main]]
     name = "Om oss"
    identifier = "om-oss"
     title = "Om oss"
     url = "/om-oss/"
     weight = "4"

 [[languages.no.menu.main]]
     name = "kontakt"
     identifier = "kontakt"
     title = "kontakt"
     url = "/kontakt/"
     weight = "5"




#Menu english
[[languages.en.menu.main]]
url    = "/"
name   = "Home"
weight = "0"

[[languages.en.menu.main]]
    name = "Ignite Analytics"
    identifier = "ignite-analytics"
    title = "Ignite Analytics"
    url = "/en/ignite-analytics/"
     weight = "1"

[[languages.en.menu.main]]
    name = "Ignite Academy"
    identifier = "ignite-academy"
    title = "Ignite Academy"
    url = "/en/ignite-academy/"
    weight = "2"

[[languages.en.menu.main]]
    name = "Ignite Services"
    identifier = "ignite-services"
    title = "Ignite Services"
     url = "/en/ignite-services/"
     id = "ignite-services"
    weight = "3"

[[languages.en.menu.main]]
    name = "About"
    identifier = "about"
    title = "About"
    url = "/en/om-oss/"
    weight = "4"

[[languages.en.menu.main]]
    name = "Contact"
    identifier = "kontakt"
    title = "kontakt"
    url = "/en/kontakt/"
    weight = "5"
