baseURL = "https://beta.ignite.no"
DefaultContentLanguage = "no"
languageName = "No"
languageCode = "no"
title = "Ignite Procurement"
publishDir = "docs"
weight = 1

[params]
logo = "/images/logo.svg"

# Header
header = "Reduser dine innkjøpskostnader"
description = "Vi hjelper deg med å optimaliser dine innkjøp ved hjelp av vårt verktøy Ignite Analytics og våre konsulenter som er eksperter på strategiske innkjøp."
image = "/images/infographics/dashboard2.svg"


[languages]
  [languages.no]
    languageName = "No"
    languageCode = "no"
    weight = "1"

  [languages.en]
    languageName = "En"
    languageCode = "en"
    weight = "2"

 
[[languages.no.menu.services]]
    name = "Ignite Analytics"
     identifier = "ignite-analytics"
     title = "Ignite Analytics"
     url = "/ignite-analytics/"
     weight = "1"

[[languages.no.menu.services]]
    name = "Ignite Academy"
     identifier = "ignite-academy"
     title = "Ignite Academy"
     url = "/ignite-academy/"
     weight = "2"

[[languages.no.menu.services]]
     name = "Ignite Services"
     identifier = "ignite-services"
     title = "Ignite Services"
     url = "/ignite-services/"
     id = "ignite-services"
     weight = "3"

[[languages.no.menu.main]]
     name = "Om selskapet"
    identifier = "om-selskapet"
     title = "Om selskapet"
     url = "/om-oss/"
     weight = "4"
     hasChildren = "true"



     
[[languages.no.menu.main]]
     name = "Innsikt"
    identifier = "innsikt"
     title = "Innsikt"
     url = "https://medium.com/ignite-procurement"
     weight = "5"


 [[languages.no.menu.secondary]]
     name = "kontakt"
     identifier = "kontakt"
     title = "kontakt"
     url = "/kontakt/"
     weight = "1"

[[languages.no.menu.secondary]]
     name = "Logg inn"
     identifier = "logg inn"
     title = "Logg inn"
     url = "https://app.ignite.no/dashboard/"
     weight = "2"



[[languages.en.menu.services]]
    name = "Ignite Analytics"
    identifier = "ignite-analytics"
    title = "Ignite Analytics"
    url = "/en/ignite-analytics/"
     weight = "1"

[[languages.en.menu.services]]
    name = "Ignite Academy"
    identifier = "ignite-academy"
    title = "Ignite Academy"
    url = "/en/ignite-academy/"
    weight = "2"

[[languages.en.menu.services]]
    name = "Ignite Services"
    identifier = "ignite-services"
    title = "Ignite Services"
     url = "/en/ignite-services/"
     id = "ignite-services"
    weight = "3"

[[languages.en.menu.main]]
    name = "About"
    identifier = "about"
    title = "About"
    url = "/en/om-oss/"
    weight = "4"

[[languages.en.menu.main]]
    name = "Insight"
    identifier = "insight"
    title = "Insight"
    url = "https://medium.com/ignite-procurement"
    weight = "4"    

[[languages.en.menu.secondary]]
    name = "Contact"
    identifier = "kontakt"
    title = "kontakt"
    url = "/en/kontakt/"
    weight = "5"

[[languages.en.menu.secondary]]
     name = "Log in"
     identifier = "log in"
     title = "Log in"
     url = "https://app.ignite.no/"
     weight = "6"
