baseURL = "https://beta.ignite.no"
languageCode = "no"
title = "Ignite Procuement"
publishDir = "docs"

[params]
    logo = "/images/logo.svg"

    # Frontpage
    header = "Reduser dine innkjøpskostnader"
    description = "Vi hjelper deg med å optimaliser dine innkjøp ved hjelp av vårt verktøy Ignite Analytics og våre konsulenter som er eksperter på strategiske innkjøp."
    image = "/images/infographics/dashboard2.svg"

 


[menu]
 

    [[menu.main]]
        name = "Ignite Analytics"
        identifier = "ignite-analytics"
        title = "Ignite Analytics"
        url = "/ignite-analytics/"
        weight = 1

    [[menu.main]]
        name = "Ignite Academy"
        identifier = "ignite-academy"
        title = "Ignite Academy"
        url = "/ignite-academy/"
        weight = 2

    [[menu.main]]
        name = "Ignite Services"
        identifier = "ignite-services"
        title = "Ignite Services"
        url = "/ignite-services/"
        id = "ignite-services"
        weight = 3

    [[menu.main]]
        name = "About"
        identifier = "about"
        title = "About"
        url = "/about/"
        weight = 4

    [[menu.main]]
        name = "kontakt"
        identifier = "kontakt"
        title = "kontakt"
        url = "/kontakt/"
        weight = 5


