baseURL = "https://ignite.no/"
DefaultContentLanguage = "no"
languageName = "No"
languageCode = "no"
title = "Ignite Procurement"
publishDir = "docs"
weight = 1

[params]
logo = "/images/logo.svg"

# Header
header = "Reduser dine innkjøpskostnader"
description = "Vi hjelper deg med å optimaliser dine innkjøp ved hjelp av vårt verktøy Ignite Analytics og våre konsulenter som er eksperter på strategiske innkjøp."
image = "/images/infographics/dashboard2.svg"


[languages]
  [languages.no]
    languageName = "No"
    languageCode = "no"
    weight = "1"

  [languages.en]
    languageName = "Eng"
    languageCode = "en"
    weight = "2"

 
[[languages.no.menu.services]]
    name = "Ignite Analytics"
     identifier = "ignite-analytics"
     title = "Ignite Analytics"
     url = "/ignite-analytics/"
     weight = "1"

[[languages.no.menu.services]]
    name = "Ignite Academy"
     identifier = "ignite-academy"
     title = "Ignite Academy"
     url = "/ignite-academy/"
     weight = "2"

[[languages.no.menu.services]]
     name = "Ignite Services"
     identifier = "ignite-services"
     title = "Ignite Services"
     url = "/ignite-services/"
     id = "ignite-services"
     weight = "3"

[[languages.no.menu.main]]
     name = "Selskapet"
    identifier = "selskapet"
     title = "selskapet"
     url = "/om-oss/"
     weight = "4"
     hasChildren = "true"

     [[languages.no.menu.main]]
            parent = "selskapet"
            name = "Om oss"
            identifier = "Om oss"
            title = "Om oss"
            url = "/om-oss"
            weight = "1"

      [[languages.no.menu.main]]
            parent = "selskapet"
            name = "Team"
            identifier = "Team"
            title = "Team"
            url = "/om-oss/#team"
            weight = "2"

      [[languages.no.menu.main]]
            parent = "selskapet"
            name = "Karriere"
            identifier = "Karriere"
            title = "Karriere"
            url = "/karriere"
            weight = "3"            


[[languages.no.menu.main]]
     name = "Blogg"
    identifier = "blogg"
     title = "Blogg"
     url = "https://medium.com/ignite-procurement"
     weight = "5"
     hasChildren = "true"

        [[languages.no.menu.main]]
            parent = "blogg"
            name = "Innsikt"
            identifier = "innsikt"
            title = "Innsikt"
            url = "https://medium.com/ignite-procurement/insight/home"
            weight = "1"

         [[languages.no.menu.main]]
            parent = "blogg"
            name = "Caser"
            identifier = "caser"
            title = "Caser"
            url = "https://medium.com/ignite-procurement/cases/home"
            weight = "2"  

            [[languages.no.menu.main]]
            parent = "blogg"
            name = "Nyheter"
            identifier = "nyheter"
            title = "Nyheter"
            url = "https://medium.com/ignite-procurement/news/home"
            weight = "3" 

    

 [[languages.no.menu.secondary]]
     name = "Kontakt oss"
     identifier = "kontakt oss"
     title = "Kontakt oss"
     url = "/kontakt/"
     weight = "1"

[[languages.no.menu.secondary]]
     name = "Logg inn"
     identifier = "logg inn"
     title = "Logg inn"
     url = "https://app.ignite.no/dashboard/"
     weight = "2"

[[languages.no.menu.btn]]
     name = "Book demo"
     identifier = "#modalbooknor"
     title = "Book demo"
     id = "#modalbook"
     weight = "1"   

[[languages.no.menu.personvern]]
     name = "Cookies og personvernerklæring"
     identifier = "personvernerklæring"
     title = "personvernerklæring"
     url = "/personvernerklæring"
     weight = "1"        





[[languages.en.menu.services]]
    name = "Ignite Analytics"
    identifier = "ignite-analytics"
    title = "Ignite Analytics"
    url = "/en/ignite-analytics/"
     weight = "1"

[[languages.en.menu.services]]
    name = "Ignite Academy"
    identifier = "ignite-academy"
    title = "Ignite Academy"
    url = "/en/ignite-academy/"
    weight = "2"

[[languages.en.menu.services]]
    name = "Ignite Services"
    identifier = "ignite-services"
    title = "Ignite Services"
     url = "/en/ignite-services/"
     id = "ignite-services"
    weight = "3"

[[languages.en.menu.main]]
    name = "Company"
    identifier = "company"
    title = "Company"
    url = "/en/om-oss/"
    weight = "4"
    hasChildren = "true"

     [[languages.en.menu.main]]
            parent = "company"
            name = "About us"
            identifier = "About us"
            title = "about us"
            url = "/en/om-oss"
            weight = "1"

      [[languages.en.menu.main]]
            parent = "company"
            name = "Team"
            identifier = "Team"
            title = "Team"
            url = "/en/om-oss/#team"
            weight = "2"

      [[languages.en.menu.main]]
            parent = "company"
            name = "Career"
            identifier = "Career"
            title = "Career"
            url = "/en/karriere"
            weight = "3"            


  
[[languages.en.menu.main]]
     name = "Blog"
    identifier = "blog"
     title = "Blog"
     url = "https://medium.com/ignite-procurement"
     weight = "5"
     hasChildren = "true"

        [[languages.en.menu.main]]
            parent = "blog"
            name = "Insight"
            identifier = "insight"
            title = "insight"
            url = "https://medium.com/ignite-procurement/insight/home"
            weight = "1"

         [[languages.en.menu.main]]
            parent = "blog"
            name = "Cases"
            identifier = "cases"
            title = "Cases"
            url = "https://medium.com/ignite-procurement/cases/home"
            weight = "2"  

            [[languages.en.menu.main]]
            parent = "blog"
            name = "News"
            identifier = "news"
            title = "News"
            url = "https://medium.com/ignite-procurement/news/home"
            weight = "3" 


[[languages.en.menu.secondary]]
    name = "Contact"
    identifier = "kontakt"
    title = "kontakt"
    url = "/en/kontakt/"
    weight = "1"

[[languages.en.menu.secondary]]
     name = "Log in"
     identifier = "log in"
     title = "Log in"
     url = "https://app.ignite.no/"
     weight = "2"

     [[languages.en.menu.btn]]
     name = "Book demo"
     identifier = "#modalbook"
     title = "Book demo"
     id = "#modalbook"
     weight = "3" 

[[languages.en.menu.personvern]]
     name = "Privacy policy"
     identifier = "personvernerklæring"
     title = "personvernerklæring"
     url = "/en/privacy-policy"
     weight = "1"      





#FOOTER
