baseURL = "https://ignite.no/"
DefaultContentLanguage = "no"
languageName = "No"
languageCode = "no"
publishDir = "docs"
weight = 1



[params]
     logos = "/images/thumb.png"
     shorttitle = "Ignite Procurement"
logo = "/images/logo.svg"
# Blog content ==>
[taxonomies]
     tag = "tags"
     category = "categories"
[permalinks]
    categories = "blogg/:slug/"
    tags = "blogg/tag/:slug"
# <==





# language support # no / en / other... translations present in i18n/

[languages]
     [languages.no]
          languageName = "No"
          languageCode = "no"
          weight = "1"
          thumbnail = "/images/ignite-services.jpg/"
          title = "Ignite Procurement - Oppdag kraften i strategisk innkjøp gjort digitalt"
          description = "Det er utfordrende å realisere det fulle potensialet innen innkjøp. Med Ignite har det aldri vært enklere – la oss hjelpe deg til en forenklet hverdag og forbedret lønnsomhet!"

     [languages.en]
          languageName = "Eng"
          languageCode = "en"
          weight = "2"
          title = "Ignite Procurement - Unlock the power of strategic procurement made digital "
          description = "Realizing the full potential within procurement is challenging. With Ignite it has never been easier – let us help you simplify everyday life and improve profitability!"
          thumbnail = "/images/ignite-services.jpg/"
#Norwegian menu
#------------
[[languages.no.menu.content]]
     hasChildren="false"
     name = "analytics"
     identifier = "analytics"
     title = "Ignite Analytics"
     url = "/ignite-analytics"
     weight = "1"
     classes="ul-analytics"

[[languages.no.menu.content]]
     hasChildren="true"
     name = "allservices"
     identifier = "allservices"
     title = "Andre Tjenester"
     url = "#"
     weight = "2"
     
     [[languages.no.menu.content]]
          parent="allservices"
          name = "academy"
          identifier = "academy"
          description = "Få mer ut av dine innkjøpsaktiviteter gjennom beste-praksis-maler, online videoer og mer"
          title = "Ignite Academy"
          url = "/ignite-academy"
          weight = "1"
          classes="ul-academy"
     
     [[languages.no.menu.content]]
          parent="allservices"
          name = "services"
          identifier = "services"
          description = "Erfarne konsulenter er tilgjengelige for å skape raske resultater gjennom skreddersydde løsninger"
          title = "Ignite Services"
          url = "/ignite-services"
          weight = "2"
          classes="ul-services"

[[languages.no.menu.content]]
     hasChildren="true"
     name = "blogg"
     identifier = "blogg"
     title = "Blogg"
     url = "/blogg/"
     weight = "3"

     [[languages.no.menu.content]]
          parent = "blogg"
          name = "Siste"
          identifier = "siste"
          title = "SISTE"
          url = "/blogg/"
          weight = "1"
     
     [[languages.no.menu.content]]
          parent = "blogg"
          name = "Innsikt"
          identifier = "innsikt"
          title = "Innsikt"
          url = "/blogg/innsikt/"
          weight = "2"
     
     [[languages.no.menu.content]]
          parent = "blogg"
          name = "Caser"
          identifier = "caser"
          title = "Caser"
          url = "/blogg/cases/"
          weight = "3"  
     [[languages.no.menu.content]]
          parent = "blogg"
          name = "Nyheter"
          identifier = "nyheter"
          title = "Nyheter"
          url = "/blogg/nyheter/"
          weight = "4"



[[languages.no.menu.content]]
     hasChildren="true"
     name = "selskapet"
     identifier = "selskapet"
     title = "Selskapet"
     url = "/om-oss/"
     weight = "4"

     [[languages.no.menu.content]]
          parent = "selskapet"
          name = "Om oss"
          identifier = "Om oss"
          title = "Om oss"
          url = "/om-oss"
          weight = "1"
     
     [[languages.no.menu.content]]
          parent = "selskapet"
          name = "Team"
          identifier = "Team"
          title = "Team"
          url = "/om-oss/#team"
          weight = "2"
     
     [[languages.no.menu.content]]
          parent = "selskapet"
          name = "partnere"
          identifier = "partnere"
          title = "Partnere"
          url = "#"
          weight = "3"   

     [[languages.no.menu.content]]
          parent = "selskapet"
          name = "Karriere"
          identifier = "Karriere"
          title = "Karriere"
          url = "/karriere"
          weight = "4"   

[[languages.no.menu.content]]
     name = "Kontakt oss"
     identifier = "kontakt oss"
     title = "Kontakt oss"
     url = "/kontakt/"
     weight = "5"

[[languages.no.menu.content]]
     name = "Prøv Ignite Analytics"
     identifier = "demo"
     title = "Book demo"
     url = "/ignite-analytics/demo"
     weight = "6"  

[[languages.no.menu.content]]
     name = "Logg inn"
     identifier = "logg inn"
     title = "Logg inn"
     url = "https://app.ignite.no/dashboard/"
     weight = "7"

[[languages.no.menu.content]]
     onlyfooter="true"
     name = "Book møte"
     identifier = "#modalbooknorw"
     title = "Book demo"
     id = "#modalbooknorw"
     weight = "8"        


#English menu
#------------
[[languages.en.menu.content]]
     hasChildren="false"
     name = "Ignite Analytics"
     identifier = "ignite-analytics"
     title = "Ignite Analytics"
     url = "/en/ignite-analytics/"
     weight = "1"

[[languages.en.menu.content]]
     hasChildren="true"
     name = "allservices"
     identifier = "allservices"
     title = "Other services"
     url = "#"
     weight = "2"
     
     [[languages.en.menu.content]]
          parent="allservices"
          name = "Ignite Academy"
          identifier = "ignite-academy"
          title = "Ignite Academy"
          url = "/en/ignite-academy/"
          weight = "1"
     
     [[languages.en.menu.content]]
          parent="allservices"
          name = "Ignite Services"
          identifier = "ignite-services"
          title = "Ignite Services"
          url = "/en/ignite-services/"
          id = "ignite-services"
          weight = "2"

[[languages.en.menu.content]]
     name = "Blog"
     identifier = "blog"
     title = "Blog"
     url = "/blogg/"
     weight = "3"
     hasChildren = "true"

     [[languages.en.menu.content]]
          parent = "blog"
          name = "Latest"
          identifier = "latest"
          title = "LATEST"
          url = "/blogg/"
          weight = "1"

     [[languages.en.menu.content]]
          parent = "blog"
          name = "Insight"
          identifier = "insight"
          title = "Insight"
          url = "/blogg/innsikt/"
          weight = "2"

     [[languages.en.menu.content]]
          parent = "blog"
          name = "Cases"
          identifier = "cases"
          title = "Cases"
          url = "/blogg/cases/"
          weight = "3"  

     [[languages.en.menu.content]]
          parent = "blog"
          name = "News"
          identifier = "news"
          title = "News"
          url = "/blogg/nyheter/"
          weight = "4"  



[[languages.en.menu.content]]
     hasChildren="true"
     name = "company"
     identifier = "company"
     title = "Company"
     url = "/om-oss/"
     weight = "4"

     [[languages.en.menu.content]]
          parent = "company"
          name = "About us"
          identifier = "About us"
          title = "about us"
          url = "/en/om-oss"
          weight = "1"

     [[languages.en.menu.content]]
          parent = "company"
          name = "Team"
          identifier = "Team"
          title = "Team"
          url = "/en/om-oss/#team"
          weight = "2"

     [[languages.no.menu.content]]
          parent = "company"
          name = "partnere"
          identifier = "partnere"
          title = "Partners"
          url = "#"
          weight = "3" 
     
     [[languages.en.menu.content]]
          parent = "company"
          name = "Career"
          identifier = "Career"
          title = "Career"
          url = "/en/karriere"
          weight = "4"             

[[languages.en.menu.content]]
     name = "Contact us"
     identifier = "kontakt"
     title = "kontakt"
     url = "/en/kontakt/"
     weight = "5"

[[languages.en.menu.content]]
     name = "Try Ignite Analytics"
     identifier = "demo"
     title = "Book demo"
     url = "/en/ignite-analytics/demo"
     weight = "6"  

[[languages.en.menu.content]]
     name = "Log in"
     identifier = "log in"
     title = "Log in"
     url = "https://app.ignite.no/"
     weight = "7"

[[languages.en.menu.content]]
     onlyfooter="true"
     name = "Book meeting"
     identifier = "#modalbookeng"
     title = "Book meeting"
     id = "#modalbooknorw"
     weight = "10"     
   

[[languages.en.menu.personvern]]
     name = "Privacy policy"
     identifier = "personvernerklæring"
     title = "personvernerklæring"
     url = "/en/privacy-policy"
     weight = "1"      

[[languages.no.menu.personvern]]
     name = "Personvernerklæring"
     identifier = "personvernerklæring"
     title = "personvernerklæring"
     url = "/personvernerklæring"
     weight = "1"       
#FOOTER
